/**
 * Injects JSON-LD structured data. Server component — raw
 * <script type="application/ld+json">, zero client JS.
 * Pass one schema object or an array.
 */
type Schema = Record<string, unknown>;

export function JsonLd({ data }: { data: Schema | Schema[] }) {
  const json = JSON.stringify(data);
  return (
    <script
      type="application/ld+json"
      // Generated by our own builders (no user input) → safe to inline.
      dangerouslySetInnerHTML={{ __html: json }}
    />
  );
}
